name: daisan-corp
favicon: null
layout_spectrum: 0.50251
typography_spectrum: 0.4207
title: HOME
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#ed203a'
    - '#979294'
    - '#000000'
    - '#5f5f5f'
  brandStrength: 0
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
